use QLDT1
go

--Cau 1
select DISTINCT DT.MADT, DT.TENDT
from (GIAOVIEN GV join GIAOVIEN GV1 on (GV.MABM=GV1.MABM and GV1.HOTEN like N'Trần Trà Hương')) join
(THAMGIADT TGDT join (DETAI DT join BOMON BM on DT.GVCNDT=BM.TRUONGBM and BM.MABM = 'CNPM') on TGDT.MADT=DT.MADT)
on GV.MAGV=TGDT.MAGV
go
--Cau 2
select DISTINCT CD.MACD, CD.TENCD
from ((CHUDE CD join DETAI DT on CD.MACD=DT.MACD) join THAMGIADT TGDT on TGDT.MADT=DT.MADT) join GIAOVIEN GV on GV.MAGV=TGDT.MAGV
where GV.MABM='HTTT' or GV.MABM='CNPM'
go