use QLDT1
GO

--Q35. Cho	biết	mức	lương	cao	nhất	của	các	giảng	viên
SELECT DISTINCT GV.LUONG 
FROM GIAOVIEN GV
WHERE LUONG>=ALL(SELECT GV1.LUONG FROM GIAOVIEN GV1)
GO

--Q36. Cho	biết	những	giáo	viên	có	lương	lớn	nhất.
SELECT GV.*
FROM GIAOVIEN GV
WHERE LUONG>=ALL(SELECT GV1.LUONG FROM GIAOVIEN GV1)
GO

--Q37. Cho	biết	lương	cao	nhất	trong	bộ môn	“HTTT”
SELECT DISTINCT GV.LUONG
FROM GIAOVIEN GV
WHERE MABM='HTTT' AND LUONG>=ALL(SELECT GV1.LUONG 
								FROM GIAOVIEN GV1
								WHERE GV1.MABM='HTTT')
GO

--Q38. Cho	biết	tên	giáo	viên	lớn	tuổi	nhất	của	bộ môn	Hệ thống	thông	tin.
SELECT DISTINCT GV.HOTEN
FROM GIAOVIEN GV JOIN BOMON BM ON GV.MABM=BM.MABM
WHERE BM.TENBM=N'Hệ thống thông tin' AND GV.NGSINH<=ALL(SELECT GV1.NGSINH 
												FROM GIAOVIEN GV1 JOIN BOMON BM1 ON GV1.MABM=BM1.MABM	
												WHERE  BM1.TENBM=N'Hệ thống thông tin')
GO

--Q39. Cho	biết	tên	giáo	viên	nhỏ tuổi	nhất	khoa	Công	nghệ thông	tin
SELECT DISTINCT GV.HOTEN
FROM (GIAOVIEN GV JOIN BOMON BM ON GV.MABM=BM.MABM) JOIN KHOA K ON BM.MAKHOA=K.MAKHOA
WHERE K.TENKHOA=N'Công nghệ thông tin' AND GV.NGSINH>=ALL(SELECT GV1.NGSINH 
												FROM GIAOVIEN GV1 JOIN BOMON BM1 ON GV1.MABM=BM1.MABM
												JOIN KHOA K1 ON BM1.MAKHOA=K1.MAKHOA
												WHERE K1.TENKHOA=N'Công nghệ thông tin')
GO

--- Q40. Cho biết tên giáo viên	và tên khoa của	giáo viên	có	lương	cao	nhất.
SELECT DISTINCT GV.HOTEN, K.TENKHOA
FROM (GIAOVIEN GV JOIN BOMON BM ON GV.MABM=BM.MABM) JOIN KHOA K ON BM.MAKHOA=K.MAKHOA
WHERE  GV.LUONG>=ALL(SELECT GV1.LUONG 
					FROM GIAOVIEN GV1)
GO

-- Q41. Cho	biết	những	giáo	viên	có	lương	lớn	nhất	trong	bộ môn	của	họ
SELECT DISTINCT GV.MAGV, GV.HOTEN, GV.MABM, GV.LUONG
FROM GIAOVIEN GV 
GROUP BY GV.MAGV, GV.HOTEN, GV.MABM, GV.LUONG
HAVING  GV.LUONG>=ALL(SELECT GV1.LUONG 
					FROM GIAOVIEN GV1
					WHERE GV.MABM=GV1.MABM
					GROUP BY GV1.MAGV, GV1.HOTEN, GV1.MABM, GV1.LUONG)
GO

-- Q42. Cho	biết	tên	những	đề tài	mà	giáo	viên	Nguyễn	Hoài	An	chưa	tham	gia.
SELECT DT.TENDT
FROM DETAI DT
WHERE DT.MADT NOT IN (SELECT TG.MADT
					FROM GIAOVIEN GV JOIN THAMGIADT TG ON GV.MAGV = TG.MAGV
					WHERE GV.HOTEN = N'Nguyễn Hoài An')
GO
 
-- Q43. Cho	biết	những	đề tài	mà	giáo	viên	Nguyễn	Hoài	An	chưa	tham	gia.	Xuất	ra	tên	đề tài,	tên	người	chủ nhiệm	đề tài.
SELECT DT.TENDT, CNDT.HOTEN
FROM DETAI DT JOIN GIAOVIEN CNDT ON DT.GVCNDT=CNDT.MAGV
WHERE DT.MADT NOT IN (SELECT TG.MADT
					FROM GIAOVIEN GV JOIN THAMGIADT TG ON GV.MAGV = TG.MAGV
					WHERE GV.HOTEN=N'Nguyễn Hoài An')
GO

-- Q44. Cho	biết	tên	những	giáo	viên	khoa	Công	nghệ thông	tin	mà	chưa	tham	gia	đề tài	nào.
SELECT DISTINCT GV.HOTEN
FROM (GIAOVIEN GV JOIN BOMON BM ON GV.MABM=BM.MABM) JOIN KHOA K ON BM.MAKHOA=K.MAKHOA
WHERE K.TENKHOA=N'Công nghệ thông tin' AND NOT EXISTS (SELECT TG.MAGV FROM THAMGIADT TG)
GO

-- Q45. Tìm	những	giáo	viên	không	tham	gia	bất	kỳ đề tài	nào
SELECT GV.*
FROM GIAOVIEN GV
WHERE GV.MAGV NOT IN (SELECT TG.MAGV FROM THAMGIADT TG)
GO

-- Q46. Cho	biết	giáo	viên	có	lương	lớn	hơn	lương	của	giáo	viên	“Nguyễn	Hoài	An”
SELECT GV.*
FROM GIAOVIEN GV
WHERE GV.LUONG > (SELECT NHA.LUONG 
					FROM GIAOVIEN NHA
					WHERE NHA.HOTEN = N'Nguyễn Hoài An')
GO

-- Q47. Tìm	những trưởng	bộ môn	tham	gia	tối	thiểu	1	đề tàiSELECT GV.MAGV, GV.HOTEN, BM.MABMFROM GIAOVIEN GV JOIN BOMON BM ON GV.MAGV=BM.TRUONGBMWHERE GV.MAGV IN (SELECT TG.MAGV FROM THAMGIADT TG)GO-- Q48. Tìm	giáo	viên	trùng	tên	và	cùng	giới	tính	với	giáo	viên	khác	trong	cùng	bộ mônSELECT GV.*FROM GIAOVIEN GVWHERE EXISTS (SELECT GV1.*			FROM GIAOVIEN GV1			WHERE GV.MAGV<>GV1.MAGV AND GV.HOTEN=GV1.HOTEN AND GV.PHAI=GV1.PHAI AND GV.MABM=GV1.MABM)GO-- Q49. Tìm	những	giáo	viên	có	lương	lớn	hơn	lương	của	ít	nhất	một	giáo	viên	bộ môn	“Công nghệ phần	mềm”SELECT GV.*FROM GIAOVIEN GVWHERE GV.LUONG > ANY(SELECT CNPM.LUONG					FROM GIAOVIEN CNPM JOIN BOMON BM ON CNPM.MABM=BM.MABM					WHERE BM.TENBM=N'Công nghệ phần mềm')GO-- Q50. Tìm	những	giáo	viên	có	lương	lớn	hơn	lương	của	tất	cả giáo	viên	thuộc	bộ môn	“Hệ thống	thông	tin”SELECT GV.*FROM GIAOVIEN GVWHERE GV.LUONG > ALL(SELECT CNPM.LUONG					FROM GIAOVIEN CNPM JOIN BOMON BM ON CNPM.MABM=BM.MABM					WHERE BM.TENBM=N'Hệ thống thông tin')GO-- Q51. Cho	biết	tên	khoa	có	đông	giáo	viên	nhấtSELECT K.TENKHOA
FROM (GIAOVIEN GV JOIN BOMON BM ON GV.MABM=BM.MABM) JOIN KHOA K ON BM.MAKHOA=K.MAKHOAGROUP BY K.MAKHOA, K.TENKHOAHAVING COUNT(*) >= ALL(SELECT COUNT(*)						FROM (GIAOVIEN GV JOIN BOMON BM ON GV.MABM=BM.MABM) JOIN KHOA K ON BM.MAKHOA=K.MAKHOA						GROUP BY K.MAKHOA, K.TENKHOA )GO-- Q52. Cho	biết	họ tên	giáo	viên	chủ nhiệm	nhiều	đề tài	nhấtSELECT GV.HOTENFROM GIAOVIEN GV JOIN DETAI DT ON GV.MAGV = DT.GVCNDTGROUP BY GV.MAGV, GV.HOTENHAVING COUNT(*) >= ALL (SELECT COUNT(*)						FROM GIAOVIEN GV1 JOIN DETAI DT1 ON GV1.MAGV = DT1.GVCNDT						GROUP BY GV1.MAGV, GV1.HOTEN)GO-- Q53. Cho	biết	mã	bộ môn	có	nhiều	giáo	viên	nhấtSELECT GV.MABMFROM GIAOVIEN GVGROUP BY GV.MABMHAVING COUNT(*)>= ALL(SELECT COUNT(*)						FROM GIAOVIEN GV1						GROUP BY GV1.MABM)GO-- Q54. Cho	biết	tên	giáo	viên	và	tên	bộ môn	của	giáo	viên	tham	gia	nhiều	đề tài	nhất.SELECT GVNDT.HOTEN, BM.TENBMFROM (SELECT GV.HOTEN, GV.MABM		FROM GIAOVIEN GV JOIN THAMGIADT TG ON GV.MAGV=TG.MAGV		GROUP BY GV.MAGV, GV.HOTEN, GV.MABM		HAVING COUNT(*)>= ALL(SELECT COUNT(*)								FROM GIAOVIEN GV JOIN THAMGIADT TG ON GV.MAGV=TG.MAGV								GROUP BY GV.MAGV, GV.HOTEN, GV.MABM)) GVNDT JOIN BOMON BM ON GVNDT.MABM=BM.MABMGO-- Q55. Cho	biết	tên	giáo	viên	tham	gia	nhiều	đề tài	nhất	của	bộ môn	HTTT.SELECT GV.HOTENFROM GIAOVIEN GV JOIN THAMGIADT TG ON GV.MAGV=TG.MAGVWHERE GV.MABM='HTTT'GROUP BY GV.MAGV, GV.HOTENHAVING COUNT(*)>=ALL(SELECT COUNT(*)					FROM GIAOVIEN GV1 JOIN THAMGIADT TG1 ON GV1.MAGV=TG1.MAGV					WHERE GV1.MABM='HTTT'					GROUP BY GV1.MAGV, GV1.HOTEN)GO-- Q56. Cho	biết	tên	giáo	viên	và	tên	bộ môn	của	giáo	viên	có	nhiều	người	thân	nhất.SELECT GV.HOTEN, BM.TENBMFROM GIAOVIEN GV JOIN BOMON BM ON GV.MABM=BM.MABMWHERE MAGV IN (SELECT NT.MAGV 				FROM NGUOITHAN NT				GROUP BY NT.MAGV				HAVING COUNT(*) >= ALL (SELECT COUNT(*)										FROM NGUOITHAN NT1										GROUP BY NT1.MAGV))GO-- Q57. Cho	biết	tên	trưởng	bộ môn	mà	chủ nhiệm	nhiều	đề tài	nhất.SELECT GV.HOTENFROM GIAOVIEN GV JOIN (SELECT BM.TRUONGBM						FROM BOMON BM JOIN DETAI DT ON BM.TRUONGBM=DT.GVCNDT						GROUP BY BM.MABM,BM.TRUONGBM						HAVING COUNT(*) >= ALL(SELECT COUNT(*)												FROM BOMON BM JOIN DETAI DT ON BM.TRUONGBM=DT.GVCNDT												GROUP BY BM.MABM,BM.TRUONGBM)) TBM ON GV.MAGV=TBM.TRUONGBMGO


						
